### ISSUE TITLE
So here it is...

### ISSUE THREAD

**Issue by j-fu** [JuliaGeometry/Triangulate.jl#1]
Hi, @SimonDanisch, @konsim83,  @furio

 so I started his package from the content of [TriangleRaw](https://github.com/j-fu/TriangleRaw.jl),
at least tests are running.

First obstacle: 
We cannot have a struct TriangulateIO.TriangulateIO. So naming the module after
the datastructure it exports was  not my best idea. 
Now it is TriangulateIO.JLTriangulateIO  (there is also CTriangulateIO, so some consistency here). 
We could keep this or otherwise perhaps we would need a different name of the package...

**Comment by furio** [comment]
I think the name of the structure is fine. Why we don-t drop the IO from the package name?

**Comment by j-fu** [comment]
> I think the name of the structure is fine. Why we don-t drop the IO from the package name?
Exactly, this also came to my mind when sleeping over it... So we just would take the
method as the name...
Maybe this evening I can fix this and work on the other stuff, need to give my lecture now.

**Comment by j-fu** [comment]
Ok. "Triangulate.jl" it is now.  The struct name is back to TriangulateIO as initially intended.
Travis works for the initial setup.

**Comment by j-fu** [comment]
@SimonDanisch: I set up TriangleBuilder with the BinaryBuilder wizard and got stuck now on travis...
May be you can have a look at the error log...

All cross-compilations were ok on my laptop.

**Comment by SimonDanisch** [comment]
Can you point me to the log?

**Comment by j-fu** [comment]
The last one is
https://travis-ci.org/JuliaGeometry/TriangleBuilder/jobs/624370595

I'm getting some clues anyway. I did the wizard on my Laptop on 1.2 with BinaryBuilder v0.1.4. On travis I get  the build_tarballs  running only on Julia 1.3 with a much newer version. Last try was without the "prefix" stuff as suggested in https://julialang.org/blog/2019/11/artifacts  . 

Will download 1.3  and try to run this locally. But the question is anyway: will the new artifact system work with Julia versions <1.3  if it comes to installing packages ?
If yes,   the stuff from TriangleBuilder might be moved to Yggdrasil anway?

First I could try a manual release with the artifacts I have on my laptop...

**Comment by j-fu** [comment]
Tests go through on linux, win, mac, and windows works in my VM. Documention build fails, though.
See the job log https://travis-ci.org/JuliaGeometry/Triangulate.jl/jobs/624517081
I started the registration process, the mandatory waiting period should be over on Sunday evening.

**Comment by SimonDanisch** [comment]
That's great to hear :)

**Comment by j-fu** [comment]
Finally builds for win+linux+osx+ documentation are green. What was missing was a build step in the documenter section of .travis.yml.

... waiting for the registrator now...

**Comment by j-fu** [comment]
Registration done. v0.2.0 should work...
