### ISSUE TITLE
Old dependency version requirement?

### ISSUE THREAD

**Issue by chakravala** [JuliaGeometry/Triangulate.jl#4]
Why are the `Project.toml` dependency requirements set to outdated versions?

https://julialang.github.io/Pkg.jl/v1/compatibility/#Compatibility-1

When I try to install `Triangulate`, it downgrades my installed packages, so I decided to use `TriangleMesh` instead.

**Comment by j-fu** [comment]
Hi this is what I did check... Taking semver literally essentially means that there may be breaking changes, so I played it safe...

I anyway wanted to upgrade things to the new artifact system, so I make a new version....

**Comment by j-fu** [comment]
Ok, triggered registration of 0.5.0  which uses artifacts, so no more bindeps at the price of cutting out pre-1.3 users now...

**Comment by j-fu** [comment]
0.5.0 is there
