### ISSUE TITLE
`plot` conflicts with `Plots.plot`

### ISSUE THREAD

**Issue by jlchan** [JuliaGeometry/Triangulate.jl#7]
Would it be possible to change the name of `plot` in Triangulate.jl so that it doesn't conflict with Plots.jl?

**Comment by jlchan** [comment]
Nevermind, it's not a big issue unless I reexport `plot` in the library I'm using Triangulate.jl in.

**Comment by j-fu** [comment]
Hi, took notice of this. Agree after my own experience. I anyway want to work on the plot part if time permits, so I will think about this change,

**Comment by jlchan** [comment]
Reopening - my previous workaround doesn't work when using Triangulate with `Requires` unless the package is loaded with `using Triangulate: Triangulate` (to avoid introducing `plot`).

**Comment by j-fu** [comment]
Got annoyed with this, too, so new version is underway, Will be 2.0.0 as it is formallly breaking.

**Comment by jlchan** [comment]
Thanks!

**Comment by j-fu** [comment]
Ok it's there.

**Comment by jlchan** [comment]
that was fast. thanks!
